---
plugins: ["jest", "prettier"]
env:
  node: true
  es2020: true
  jest/globals: true

extends:
  - "airbnb-base"

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  jest/no-disabled-tests: "warn"
  jest/no-focused-tests: "error"
  jest/no-identical-title: "error"
  jest/prefer-to-have-length: "warn"
  jest/valid-expect: "error"
